const filteredUsers = [
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
  {
    role: "star",
    name: "محمد",
    govern: "الرياض",
    area: ["الرياض"],
    ads: [],
    verified: true,
    accountType: "نجم",
  },
];
